AWSTemplateFormatVersion: '2010-09-09'
Description: Template to Create an EC2 instance in a VPC & Subnet specified
Parameters:
  ImageId:
    Type: String
    Description: 'Linux 2 AMI for Ireland us-east1 Region'
    Default: 'ami-01cc34ab2709337aa'
  VpcId:
    Type: String
    Description: VPC id - Provide the VPC ID of your choice
    Default: vpc-016d064b6d261a56a
  SubnetId:
    Type: String
    Description: Subnet in which to launch an EC2 - provide the subnet of your choice in the VPC
    Default: subnet-08e5eda387d3c3ce9
  AvailabilityZone:
    Type: String
    Description: Availability Zone into which instance will launch - Should match the AZ and the AMI Id
    Default: us-east-1a
  InstanceType:
    Type: String
    Description: Choosing t2 micro because it is free
    Default: t2.micro
  KeyName:
    Description: SSH Keypair to login to the instance
    Type: AWS::EC2::KeyPair::KeyName
    ConstraintDescription: must be the name of an existing EC2 KeyPair. Create the key prior to the stack creation

Resources:
  DemoInstance:
    Type: 'AWS::EC2::Instance'
    Properties: 
      ImageId: !Ref ImageId
      InstanceType: !Ref InstanceType
      AvailabilityZone: !Ref AvailabilityZone
      KeyName: !Ref KeyName
      SecurityGroupIds: 
        - !Ref DemoSecurityGroup
      SubnetId: !Ref SubnetId
      Tags:
      - Key: Name
        Value: TestVMatSource1

  DemoSecurityGroup:
    Type: 'AWS::EC2::SecurityGroup'
    Properties:
      VpcId: !Ref VpcId
      GroupDescription: SG to allow SSH access via port 22
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: '22'
          ToPort: '22'
          CidrIp: '0.0.0.0/0'
      Tags:
        - Key: Name
          Value: SG-SSH-anyIP

Outputs:
  DemoInstanceId:
    Description: Instance Id 
    Value: !Ref DemoInstance